name: finalcquotes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  flutter_easyloading:
  flutter_card_swiper: ^7.0.1
  slider_button: ^2.1.0
  share_it: ^0.7.0
  shared_preferences:
  connection_notifier: ^2.0.1
  carousel_slider: ^4.2.1
  provider:
  cloud_firestore:
  animated_splash_screen: ^1.3.0
  change_app_package_name: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - asset/img.jpg
    - asset/img2.jpg
    - asset/img3.jpg
    - asset/img4.jpg
    - asset/img6.jpg
    - asset/img7.jpg
    - asset/pastor-amankwah.jpg


  fonts:
    - family: PoetsenOne-Regular
      fonts:
        - asset: asset/font/PoetsenOne-Regular.ttf
